# Generated by Django 4.2 on 2023-05-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_traduction_francais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=30)),
                ('francais', models.CharField(max_length=30)),
                ('soninke', models.CharField(max_length=30)),
            ],
        ),
    ]
