# Generated by Django 5.1 on 2024-12-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=30)),
                ('francais', models.CharField(max_length=30)),
                ('soninke', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Traduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('francais', models.CharField(db_index=True, max_length=255)),
                ('soninke', models.CharField(max_length=255)),
            ],
        ),
    ]
