# Generated by Django 4.2 on 2023-05-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_traduction_francais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traduction',
            name='francais',
            field=models.CharField(max_length=255),
        ),
    ]
